# Generated by Django 2.2 on 2022-12-14 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('short_name', models.CharField(max_length=100)),
                ('creation_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, unique=True)),
                ('last_name', models.CharField(max_length=100, unique=True)),
                ('middle_name', models.CharField(max_length=100, unique=True)),
                ('birthday_date', models.DateField()),
                ('enter_university_date', models.DateField()),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='university_fbv.University', to_field='name')),
            ],
        ),
    ]
